# 本地服务访问
server:
  # 服务端口
  port: 8081
  # 服务IP
  address: 0.0.0.0

spring:
  application:
    # 应用服务名
    name: gateway
  cloud:
    gateway:
      routes:
        - id: producer
          uri: http://127.0.0.1:8082
          predicates:
          - Path=/api/producer
# 配置日志
logging:
  level:
    reactor.util: info
    org.springframework.boot: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } traceID=%X{trace_id} --- [%t] %-40.40logger{39} : %m%n%wEx"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(traceID=%X{trace_id}){cyan} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: ./logs/gateway-info.log

# 是否启用springboot的debug调试模式，会打印详细日志信息
debug: false
