# 本地服务访问
server:
  # 服务端口
  port: 8082
  # 服务IP
  address: 0.0.0.0

spring:
  application:
    # 应用服务名
    name: producer
#  data:
#    redis:
#      host: localhost
#      port: 6379
  datasource:
    url: jdbc:mysql://192.168.65.150:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test_user
    password: 123456

# 配置日志
logging:
  level:
    reactor.util: info
    org.springframework.boot: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } traceID=%X{trace_id} --- [%t] %-40.40logger{39} : %m%n%wEx"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(traceID=%X{trace_id}){cyan} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: ./logs/producer-info.log

# 是否启用springboot的debug调试模式，会打印详细日志信息
debug: false